version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Polina_Z
      POSTGRES_USER: polina_user
      POSTGRES_DB: flask_test

    ports:
    - 5431:5432

